package gui;

import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.net.URL;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import enums.Enum_TabMainMenu;

public class TAB_ThanhToan extends javax.swing.JPanel{
	
	private TAB_ThanhToan tabThanhToan;
    private TAB_Thuoc tabThuoc;
	private Enum_TabMainMenu currentSelectedTab;
	private JButton isFocusTab;
	
	
	private JPanel jPanel_QuanLy;
	private JPanel jPanel_DangXuat;
	private JButton button_ThanhToan;
	private JButton button_NhanVien;
	private JButton button_NhaCungCap;
	private JButton button_DangXuat;
	private JButton button_ThongKe;
	private JButton button_Thuoc;
	private JPanel jPanel_content;
	private JPanel jPanel_NORTH;
	private JPanel jPanel_CENTER;
	private JPanel jPanel_WEST;
	
	public TAB_ThanhToan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	Font font_text = new Font("Verdana", Font.BOLD, 12);
		Font font_title = new Font("Verdana", Font.BOLD, 16);
		Font font_special = new Font("Verdana", Font.BOLD, 20);

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TAB_BanHang_DanhSachHoaDon = new javax.swing.JPanel();
        TAB_BanHang_HoaDon = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        TAB_BanHang_DanhSachHoaDon.setLayout(new BorderLayout());
        TAB_BanHang_HoaDon.setLayout(new BorderLayout());
    
        
        jPanel_content = new JPanel();
		jPanel_content.setLayout(new BorderLayout());

		
		JPanel jPanel_content_ThongTin = new JPanel();
		JPanel jPanel_content_ThanhToan = new JPanel();
		
		jPanel_content_ThongTin.setLayout(new BorderLayout());
		jPanel_content_ThanhToan.setLayout(new BorderLayout());
		
		JPanel jPanel_SanPham = new JPanel();
		JPanel jPanel_GioHang = new JPanel();
		
		jPanel_SanPham.setBorder(BorderFactory.createTitledBorder("Sản phẩm"));
		jPanel_GioHang.setBorder(BorderFactory.createTitledBorder("Giỏ hàng"));
		
		jPanel_SanPham.setLayout(new BoxLayout(jPanel_SanPham, BoxLayout.Y_AXIS));
		jPanel_GioHang.setLayout(new BorderLayout());
		
		JLabel jLabel_MaThuoc = new JLabel("Mã thuốc: ");
		JLabel jLabel_TenThuoc = new JLabel("Tên thuốc: ");
		JLabel jLabel_Gia = new JLabel("Giá: ");
		JLabel jLabel_SoLuong = new JLabel("Số lượng: ");
		
		jLabel_MaThuoc.setFont(font_text);
		jLabel_TenThuoc.setFont(font_text);
		jLabel_Gia.setFont(font_text);
		jLabel_SoLuong.setFont(font_text);
		
		JTextField jTextField_MaThuoc = new JTextField();
		JTextField jTextField_TenThuoc = new JTextField();
		JTextField jTextField_Gia = new JTextField();
		JTextField jTextField_SoLuong = new JTextField();
		
		jTextField_MaThuoc.setFont(font_text);
		jTextField_TenThuoc.setFont(font_text);
		jTextField_Gia.setFont(font_text);
		jTextField_SoLuong.setFont(font_text);
		
		
		jTextField_TenThuoc.setEditable(false);
		jTextField_Gia.setEditable(false);

		
		JPanel jPanel_SanPham_left = new JPanel();
		JPanel jPanel_SanPham_right = new JPanel();
		
		jPanel_SanPham_left.setLayout(new BoxLayout(jPanel_SanPham_left, BoxLayout.X_AXIS));
		jPanel_SanPham_right.setLayout(new BoxLayout(jPanel_SanPham_right, BoxLayout.X_AXIS));
		
		JPanel jPanel_SanPham_left_left = new JPanel();
		JPanel jPanel_SanPham_left_right = new JPanel();
		
		jPanel_SanPham_left_left.setLayout(new BoxLayout(jPanel_SanPham_left_left, BoxLayout.Y_AXIS));
		jPanel_SanPham_left_right.setLayout(new BoxLayout(jPanel_SanPham_left_right, BoxLayout.Y_AXIS));
		
		jPanel_SanPham_left_left.add(jLabel_MaThuoc);
		jPanel_SanPham_left_left.add(Box.createVerticalStrut(20));
		jPanel_SanPham_left_left.add(jLabel_Gia);
		jPanel_SanPham_left_left.add(Box.createVerticalStrut(20));
		jPanel_SanPham_left_right.add(jTextField_MaThuoc);
		jPanel_SanPham_left_right.add(Box.createVerticalStrut(20));
		jPanel_SanPham_left_right.add(jTextField_Gia);
		jPanel_SanPham_left_right.add(Box.createVerticalStrut(20));
		
		JPanel jPanel_SanPham_right_left = new JPanel();
		JPanel jPanel_SanPham_right_right = new JPanel();
		
		jPanel_SanPham_right_left.setLayout(new BoxLayout(jPanel_SanPham_right_left, BoxLayout.Y_AXIS));
		jPanel_SanPham_right_right.setLayout(new BoxLayout(jPanel_SanPham_right_right, BoxLayout.Y_AXIS));
		
		jPanel_SanPham_right_left.add(jLabel_TenThuoc);
		jPanel_SanPham_right_left.add(Box.createVerticalStrut(20));
		jPanel_SanPham_right_left.add(jLabel_SoLuong);
		jPanel_SanPham_right_left.add(Box.createVerticalStrut(20));
		jPanel_SanPham_right_right.add(jTextField_TenThuoc);
		jPanel_SanPham_right_right.add(Box.createVerticalStrut(20));
		jPanel_SanPham_right_right.add(jTextField_SoLuong);
		jPanel_SanPham_right_right.add(Box.createVerticalStrut(20));
		
		jPanel_SanPham_left.add(Box.createHorizontalStrut(20));
		jPanel_SanPham_left.add(jPanel_SanPham_left_left);
		jPanel_SanPham_left.add(jPanel_SanPham_left_right);
		
		jPanel_SanPham_right.add(Box.createHorizontalStrut(20));
		jPanel_SanPham_right.add(jPanel_SanPham_right_left);
		jPanel_SanPham_right.add(jPanel_SanPham_right_right);
		
		JButton button_Them = new JButton("Thêm");
		JButton button_Xoa= new JButton("Xóa");
		
		button_Them.setBackground(new Color(157, 224, 173));
		button_Xoa.setBackground(new Color(232, 74, 95));
		
		button_Them.setPreferredSize(new Dimension(72, 30));
		button_Xoa.setPreferredSize(new Dimension(72, 30));
		
		button_Them.setFont(font_text);
		button_Xoa.setFont(font_text);
		
		JPanel jPanel_Them_Xoa = new JPanel();
		jPanel_Them_Xoa.add(button_Them);
		jPanel_Them_Xoa.add(button_Xoa);
		
		JPanel jPanel_SanPham1 = new JPanel();
		JPanel jPanel_SanPham2 = new JPanel();
		
		jPanel_SanPham1.setLayout(new BoxLayout(jPanel_SanPham1, BoxLayout.X_AXIS));
		jPanel_SanPham2.setLayout(new BorderLayout());
		
		jPanel_SanPham1.add(jPanel_SanPham_left);
		jPanel_SanPham1.add(jPanel_SanPham_right);
		
		jPanel_SanPham2.add(jPanel_Them_Xoa, BorderLayout.EAST);
		
		jPanel_SanPham.add(jPanel_SanPham1);
		jPanel_SanPham.add(jPanel_SanPham2);
		
		JPanel jPanel_TongTien = new JPanel();
		jPanel_TongTien.setLayout(new BoxLayout(jPanel_TongTien, BoxLayout.X_AXIS));
		
		String[] column = {"STT", "Mã thuốc", "Tên thuốc", "Đơn giá", "Số lượng", "Thành tiền", "Xóa"};
		Object[][] data = {};
		DefaultTableModel table_model = new DefaultTableModel(data, column);
		
		JTable jTable = new JTable(table_model);
		jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTable.setOpaque(true);
		
		DefaultTableCellRenderer defaultTableCellRenderer = new DefaultTableCellRenderer();
		defaultTableCellRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
		defaultTableCellRenderer.setBackground(new Color(124,185,232));
		jTable.getTableHeader().setDefaultRenderer(defaultTableCellRenderer);
		
//		jTable.setFillsViewportHeight(true);
		jTable.setFont(font_text);
		
		jTable.setBackground(new Color(90,168,242));
		
		JScrollPane sp = new JScrollPane(jTable);
//		sp.setBackground(new Color(90,168,242));

		
		JLabel jLabel_TongTien = new JLabel("Tổng tiền: ");
		jLabel_TongTien.setFont(font_special);
		jLabel_TongTien.setForeground(new Color(254, 67, 101));
		JTextField jPanel_TongTien_left = new JTextField();
		
		
		jPanel_TongTien.add(jLabel_TongTien);
		jPanel_TongTien.add(jPanel_TongTien_left);
		
		
		jPanel_GioHang.add(sp, BorderLayout.CENTER);
		jPanel_GioHang.add(jPanel_TongTien, BorderLayout.SOUTH);
		
		jPanel_content_ThongTin.add(jPanel_SanPham, BorderLayout.NORTH);
		jPanel_content_ThongTin.add(jPanel_GioHang, BorderLayout.CENTER);
		
		JPanel jPanel_KhachHang = new JPanel();
		JPanel jPanel_ThaoTacThanhToan = new JPanel();
		
		jPanel_KhachHang.setLayout(new BoxLayout(jPanel_KhachHang, BoxLayout.Y_AXIS));
		jPanel_KhachHang.setBorder(BorderFactory.createTitledBorder("Khách hàng"));
		
		JPanel jPanel_TimSoDienThoai = new JPanel();
		JPanel jPanel_MaKhachHang_TenKhachHang = new JPanel();
		
		
		JPanel jPanel_ThongTinKhachHang_left = new JPanel();
		JPanel jPanel_ThongTinKhachHang_right = new JPanel();
		
		jPanel_MaKhachHang_TenKhachHang.setLayout(new BoxLayout(jPanel_MaKhachHang_TenKhachHang, BoxLayout.X_AXIS));
		
		
		//JLabel jLabel_SoDienThoai = new JLabel("Số điện thoại: ");
		JLabel jLabel_TenKhachHang= new JLabel("Tên khách hàng: ");
		JLabel jLabel_MaKhachHang = new JLabel("Mã khách hàng: ");
		
		jLabel_TenKhachHang.setFont(font_text);
		jLabel_MaKhachHang.setFont(font_text);
		
		
		JTextField jTextField_TimKhachHang = new JTextField(17);
		JTextField jTextField_MaKhachHang = new JTextField(17);
		JTextField jTextField_TenKhachHang = new JTextField(17);
		
		jTextField_MaKhachHang.setEditable(false);
		jTextField_TenKhachHang.setEditable(false);
		
		
		JButton jButton_Tim = new JButton();
		ImageIcon imageIcon_Tim = new ImageIcon("src/IMG/Find.png");
		
		Image scaled_Tim = scaleImage(imageIcon_Tim.getImage(), 10, 10);
		ImageIcon scaledIcon_Tim = new ImageIcon(scaled_Tim);
		jButton_Tim.setIcon(scaledIcon_Tim);
		
		jButton_Tim.setBackground(new Color(90,168,242));
		
		jPanel_TimSoDienThoai.add(jTextField_TimKhachHang);
		jPanel_TimSoDienThoai.add(jButton_Tim);
		
		jPanel_ThongTinKhachHang_left.setLayout(new BoxLayout(jPanel_ThongTinKhachHang_left, BoxLayout.Y_AXIS));
		jPanel_ThongTinKhachHang_right.setLayout(new BoxLayout(jPanel_ThongTinKhachHang_right, BoxLayout.Y_AXIS));
		
		jPanel_ThongTinKhachHang_left.add(jLabel_MaKhachHang);
		jPanel_ThongTinKhachHang_left.add(Box.createVerticalStrut(12));
		jPanel_ThongTinKhachHang_left.add(jLabel_TenKhachHang);
		
		jPanel_ThongTinKhachHang_right.add(jTextField_MaKhachHang);
		jPanel_ThongTinKhachHang_right.add(Box.createVerticalStrut(12));
		jPanel_ThongTinKhachHang_right.add(jTextField_TenKhachHang);

		jPanel_MaKhachHang_TenKhachHang.add(Box.createHorizontalStrut(5));
		jPanel_MaKhachHang_TenKhachHang.add(jPanel_ThongTinKhachHang_left);
		jPanel_MaKhachHang_TenKhachHang.add(jPanel_ThongTinKhachHang_right);
		jPanel_MaKhachHang_TenKhachHang.add(Box.createHorizontalStrut(5));
		
		
		jPanel_KhachHang.add(jPanel_TimSoDienThoai);
		jPanel_KhachHang.add(Box.createVerticalStrut(12));
		jPanel_KhachHang.add(jPanel_MaKhachHang_TenKhachHang);
		jPanel_KhachHang.add(Box.createVerticalStrut(26));
		
		JPanel jPanel_BanPhim = new JPanel();
		JPanel jPanel_XuLyThanhToan = new JPanel();
		
		JPanel jPanel_BanPhim_in = new JPanel();
		
		jPanel_BanPhim.setLayout(new GridLayout(4, 3));
		
		JButton jButton_1 = new JButton("1");
		JButton jButton_2 = new JButton("2");
		JButton jButton_3 = new JButton("3");
		JButton jButton_4 = new JButton("4");
		JButton jButton_5 = new JButton("5");
		JButton jButton_6 = new JButton("6");
		JButton jButton_7 = new JButton("7");
		JButton jButton_8 = new JButton("8");
		JButton jButton_9 = new JButton("9");
		JButton jButton_0 = new JButton("0");
		JButton jButton_000 = new JButton("000");
		JButton jButton_T = new JButton("T");
		
		jButton_1.setFont(font_title);
		jButton_2.setFont(font_title);
		jButton_3.setFont(font_title);
		jButton_4.setFont(font_title);
		jButton_5.setFont(font_title);
		jButton_6.setFont(font_title);
		jButton_7.setFont(font_title);
		jButton_8.setFont(font_title);
		jButton_9.setFont(font_title);
		jButton_0.setFont(font_title);
		jButton_000.setFont(font_title);
		jButton_T.setFont(font_title);
		
		
		jPanel_BanPhim.add(jButton_7);
		jPanel_BanPhim.add(jButton_8);
		jPanel_BanPhim.add(jButton_9);
		jPanel_BanPhim.add(jButton_4);
		jPanel_BanPhim.add(jButton_5);
		jPanel_BanPhim.add(jButton_6);
		jPanel_BanPhim.add(jButton_1);
		jPanel_BanPhim.add(jButton_2);
		jPanel_BanPhim.add(jButton_3);
		jPanel_BanPhim.add(jButton_0);
		jPanel_BanPhim.add(jButton_000);
		jPanel_BanPhim.add(jButton_T);
		
		
		
		jPanel_BanPhim.setPreferredSize(new Dimension(100, 310));
		
		jPanel_BanPhim_in.add(jPanel_BanPhim);
		
		JButton jButton_ThanhToan = new JButton("Thanh toán");
		JButton jButton_Huy = new JButton("Hủy");
		
		jButton_ThanhToan.setBackground(new Color(115,208,111));
		jButton_Huy.setBackground(new Color(255,90,95));
		
		jButton_ThanhToan.setFont(font_title);
		jButton_Huy.setFont(font_title);
		
		jButton_ThanhToan.setForeground(new Color(255,251,241));
		jButton_Huy.setForeground(new Color(255,251,241));
		
		jButton_ThanhToan.setPreferredSize(new Dimension(200, 50));
		jButton_Huy.setPreferredSize(new Dimension(200, 50));
		
		jPanel_XuLyThanhToan.setLayout(new GridLayout(2, 1, 10, 10));
		
		JPanel jPanel_empty = new JPanel();
		jPanel_empty.setPreferredSize(new Dimension(10, 10));
		//jPanel_XuLyThanhToan.add(jPanel_BanPhim);
		//jPanel_XuLyThanhToan.add(jPanel_empty);
		
		jPanel_XuLyThanhToan.setBorder(BorderFactory.createLineBorder(new Color(90, 168, 242), 2));
		
		jPanel_XuLyThanhToan.add(jButton_ThanhToan);
		jPanel_XuLyThanhToan.add(jButton_Huy);
		
		jPanel_content_ThanhToan.add(jPanel_KhachHang, BorderLayout.NORTH);
		
		jPanel_BanPhim.setBorder(BorderFactory.createLineBorder(new Color(90, 168, 242), 2));
		
		jPanel_content_ThanhToan.add(jPanel_BanPhim, BorderLayout.CENTER);
		jPanel_content_ThanhToan.add(jPanel_XuLyThanhToan, BorderLayout.SOUTH);
		
		jPanel_content.add(jPanel_content_ThongTin, BorderLayout.CENTER);
		jPanel_content.add(jPanel_content_ThanhToan, BorderLayout.EAST);
		
		TAB_BanHang_HoaDon.add(jPanel_content, BorderLayout.CENTER);
        
	
        jTabbedPane1.addTab("Hoá đơn", TAB_BanHang_HoaDon);
        jTabbedPane1.addTab("Danh sách hoá đơn", TAB_BanHang_DanhSachHoaDon);
        
        
//        {
//        	jTabbedPane1.setBackground(new Color(15, 145, 239));
//        }
//        TAB_BanHang_DanhSachHoaDon.setBackground(new Color(168, 230, 206));

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        
    
	private Image scaleImage(Image image, int w, int h) {
		
		
        Image scaled = image.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return scaled;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel TAB_BanHang_DanhSachHoaDon;
    private javax.swing.JPanel TAB_BanHang_HoaDon;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration                 
		

}
